version: "3.7"

services:
  app:
    build: .
    volumes:
      - ./recipeBook:/recipeBook
    env_file:
      - .env
    command: /bin/sh -c "./run.sh"
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db

  # Database
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
