# Generated by Django 4.0.2 on 2022-02-18 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientname',
            old_name='name',
            new_name='ing_name',
        ),
    ]
